FROM nginx:alpine AS dev-stage
COPY nginx.dev.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html/
EXPOSE 80


FROM nginx:alpine AS prod-stage
COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html/
EXPOSE 80
EXPOSE 443