services:
  frontend:
    build: 
      context: ./frontend
      target: dev-stage
    image: mydelivery:frontend_dev
    container_name: frontend_container
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro #挂载服务器的时间文件，避免因时区问题产生的bug
    networks:
      - delivery

