services:
  backend:
    build: ./backend
    image: crpi-bgqknwkbk03z351x.cn-beijing.personal.cr.aliyuncs.com/shr888666/mydelivery:backend1.1
    container_name: backend_container
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      BACKEND_MYSQL_USER: ${BACKEND_MYSQL_USER}
      BACKEND_MYSQL_PASSWORD: ${BACKEND_MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY}
      USER_SECRET_KEY: ${USER_SECRET_KEY}
      ALI_OSS_ENDPOINT: ${ALI_OSS_ENDPOINT}
      ALI_OSS_KEY_ID: ${ALI_OSS_KEY_ID}
      ALI_OSS_SECRET: ${ALI_OSS_SECRET}
      ALI_OSS_BUCKET: ${ALI_OSS_BUCKET}
      WECHAT_APPID: ${WECHAT_APPID}
      WECHAT_SECRET: ${WECHAT_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime:ro #挂载服务器的时间文件，避免因时区问题产生的bug
    networks:
      - delivery

  frontend:
    build: ./frontend
    image: crpi-bgqknwkbk03z351x.cn-beijing.personal.cr.aliyuncs.com/shr888666/mydelivery:frontend1.1
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro #挂载https证书，使用https加密传输
      - /etc/localtime:/etc/localtime:ro #挂载服务器的时间文件，避免因时区问题产生的bug
    networks:
      - delivery

networks:
  delivery:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
